export { ResetPassword } from './reset-password/reset-password';
export { ForgotPassword } from './forgot-password/forgot-password';
export { Login } from './login/login';
export { Main } from './main/main';
export { Register } from './register/register';
export { Profile } from './profile/profile';
export { NotFound } from './404/404';
export { OrderDetails } from './order-details/order-details'
export { Feed } from './feed/feed'
